# Generated by Django 4.0.6 on 2022-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_project',
            field=models.URLField(null=True),
        ),
    ]
