# Generated by Django 4.0.6 on 2022-07-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('biography', models.TextField(null=True, verbose_name='Biografía')),
                ('image', models.ImageField(null=True, upload_to='projects', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Biografía',
                'verbose_name_plural': 'Biografías',
            },
        ),
    ]
