# Generated by Django 4.0.6 on 2022-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(null=True, upload_to='about', verbose_name='Imagen'),
        ),
    ]
